// <auto-generated />
using System;
using CredVault.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CredVault.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CredVaultDbContext))]
    [Migration("20260528102508_AddPasswordResetTokens")]
    partial class AddPasswordResetTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CredVault.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorIpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<Guid?>("ActorServiceTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorUserAgent")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AuditLogs_OrgId_OccurredAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Credentials.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<long>("AccessCount")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("AuthTag")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("CredentialSchemaVersion")
                        .HasColumnType("int");

                    b.Property<byte[]>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("KekVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastAccessedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("MaskedPreview")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("varbinary(12)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RotatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("WrappedDataKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ExpiresAtUtc")
                        .HasDatabaseName("IX_Credentials_OrgId_ExpiresAt")
                        .HasFilter("[ExpiresAtUtc] IS NOT NULL");

                    b.HasIndex("EnvironmentId", "SupplierId", "Slug")
                        .IsUnique();

                    b.ToTable("Credentials", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Credentials.CredentialAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("AccessMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("AccessedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActorType")
                        .HasColumnType("int");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId", "AccessedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_CredentialAccessLogs_CredentialId_AccessedAt");

                    b.HasIndex("OrganizationId", "AccessedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_CredentialAccessLogs_OrgId_AccessedAt");

                    b.ToTable("CredentialAccessLogs", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Credentials.CredentialNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<byte[]>("AuthTag")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("EncryptedContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("KekVersion")
                        .HasColumnType("int");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("varbinary(12)");

                    b.Property<byte[]>("WrappedDataKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId");

                    b.ToTable("CredentialNotes", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Credentials.CredentialRotation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PreviousAuthTag")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("PreviousEncryptedPayload")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("PreviousKekVersion")
                        .HasColumnType("int");

                    b.Property<byte[]>("PreviousNonce")
                        .IsRequired()
                        .HasColumnType("varbinary(12)");

                    b.Property<byte[]>("PreviousWrappedDataKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RotatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("RotatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId", "RotatedAtUtc");

                    b.ToTable("CredentialRotations", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("OrganizationMemberships", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Projects.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Slug")
                        .IsUnique();

                    b.ToTable("Environments", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.ServiceTokens.ServiceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("HmacHash")
                        .IsRequired()
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("IpAllowlistJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HmacHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "RevokedAtUtc");

                    b.ToTable("ServiceTokens", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Suppliers.CredentialSupplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SupplierType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "SupplierType");

                    b.ToTable("CredentialSuppliers", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Users.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "UsedAtUtc");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmailLowered")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasComputedColumnSql("LOWER([Email])", true);

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MfaSecretReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("EmailLowered")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Webhooks.Webhook", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SigningSecretReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("_events")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Events");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "IsActive");

                    b.ToTable("Webhooks", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Webhooks.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("LastResponseStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SucceededAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("WebhookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAtUtc")
                        .HasDatabaseName("IX_WebhookDeliveries_DuePending")
                        .HasFilter("[SucceededAtUtc] IS NULL");

                    b.ToTable("WebhookDeliveries", (string)null);
                });

            modelBuilder.Entity("CredVault.Domain.Credentials.CredentialRotation", b =>
                {
                    b.HasOne("CredVault.Domain.Credentials.Credential", null)
                        .WithMany("Rotations")
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CredVault.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.HasOne("CredVault.Domain.Organizations.Organization", null)
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CredVault.Domain.Credentials.Credential", b =>
                {
                    b.Navigation("Rotations");
                });

            modelBuilder.Entity("CredVault.Domain.Organizations.Organization", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
